<?php


namespace MatomoReport\Response\Goals;


use MatomoReport\Entity\Goals\ItemsSkuEntity;
use MatomoReport\Response\CommentListResponse;

class GetItemsSkuResponse extends CommentListResponse
{
    /**
     * @return ItemsSkuEntity[]
     */
    public function getList(): array
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }
}