<?php


namespace MatomoReport\Response\Contents;


use MatomoReport\Entity\Contents\ContentNamesEntity;
use MatomoReport\Response\CommentListResponse;

class GetContentNamesResponse extends CommentListResponse
{
    /**
     * @return ContentNamesEntity[]
     */
    public function getList(): array
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }
}